name: Lint project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Install packages
        run: sudo apt-get -y update && sudo apt-get -y install libgl1-mesa-dev xorg-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m --enable-all --disable perfsprint,nestif,wsl,cyclop,depguard,goerr113,nlreturn,varnamelen
